### ISSUE TITLE
the generlization of this method

### ISSUE THREAD

**Issue by Adasunnylily** [Trustworthy-ML-Lab/CLIP-dissect#2]
hi, great work! 
can this method be used to access the interprebility of other work such as label-free?
thanks a lot!

**Comment by tuomaso** [comment]
Thanks!
Yes that is an interesting thing we can do. Initial results show that when CLIP-Dissect is applied to label-free cbm the labels are mostly in agreement with LF-CBM label names, in terms of having similar meaning even though the exact concept will be different. We could also use this method to compare interpretability of different models for example in terms of average similarity scores, but this is not something we have experimented with/validated carefully.
